### ISSUE TITLE
Overlay height issue

### ISSUE THREAD

**Issue by pcout** [vadimsva/waitMe#1]
Hi,

The overlay is not covering all my webpage.
If I scroll down the overlay stays fixed at the top.
I'm using $('body').waitMe();

Can you help me ?

Thanks

**Comment by vadimsva** [comment]
Hi, try to use new 1.05

**Comment by Greenelf** [comment]
version 1.15 not work

**Comment by Greenelf** [comment]
It is standard option or plugin has parameter for switch off scroll to top

**Comment by vadimsva** [comment]
Hi, height issue was fixed in 1.16. Now last version is 1.18
