### ISSUE TITLE
Add Icon Position option

### ISSUE THREAD

**Issue by ryanlin1986** [vadimsva/waitMe#10]
I have several scenario need waitMe on a elment that within 30 px height, since the waitMe icon and text are two lines, the height is greater than my element, looks ugly.
So add this option would solve my problem, any plan?

**Comment by vadimsva** [comment]
Use new ver 1.17 with param textPos: 'horizontal'

**Comment by ryanlin1986** [comment]
Thanks ;) Just what I need.
