### ISSUE TITLE
Problem with maxSize and rotation effect.

### ISSUE THREAD

**Issue by msender** [vadimsva/waitMe#14]
Hi, When using the rotation effect, if you set the maxSize it gets shifted to the left.

see screenshot.
![waitme](https://cloud.githubusercontent.com/assets/8262345/18967175/3d03a34c-8652-11e6-88bb-88c865259ec9.PNG)

**Comment by vadimsva** [comment]
Hi, fixed. Use updated 1.18

**Comment by msender** [comment]
Thanks
