### ISSUE TITLE
Does not work in Internet Explorer - 8

### ISSUE THREAD

**Issue by ttelang** [vadimsva/waitMe#2]
Steps to reproduce problem
1. Launch **IE 8**
2. Go to **Demo** Page at URL -> http://vadimsva.github.io/waitMe/
3. Click _Submit_ 

**Expected Result:** 
loading animation should work normally
**Actual Result:** 
Following console error are encountered and loading animation does not get shows up. 
- Object doesn't support this property or method  jquery.min.js, line 2 character 29694
- 'jQuery' is undefined  waitMe.js, line 6 character 1
- Object expected  waitMe, line 116 character 1

**Comment by vadimsva** [comment]
Plugin use css3 animation, and works on all browsers and IE10+.

**Comment by ttelang** [comment]
It should be possible to convert its CSS3 animation to animation effects based on jquery. Let me give it a try.

**Comment by vadimsva** [comment]
jquery animation is very slow and I don't see any reason to support older browsers, such as ie8-9. But You can do this for yourself

**Comment by ttelang** [comment]
Below is an example code snippet of how to get the loading animation work in all the browsers (including IE <10 ). This makes use of the Spin.js & Modernizr library available at following URLs: 
- Spin.js - http://fgnass.github.io/spin.js/
- Modernizr - http://modernizr.com/

```
<script src="./libs/modernizer/modernizr-2.6.2.min.js" charset="utf-8"></script>
<script src="./libs/spin.js/spin.min.js"></script>
<script>
if (!Modernizr.cssanimations || !Modernizr.csstransitions){
   // show progress bar for older browsers
    new Spinner().spin(document.body);
 } else {
    $('body').waitMe({
          effect: 'ios',
          bg: 'rgba(255,255,255,0.7)',
          color: '#000',                            
     });
}
</script>
```

**Comment by vadimsva** [comment]
Also you can use image as animation (gif, svg, ...)
Demo uses jquery 2.x, that without support <ie8
