### ISSUE TITLE
Demo is not working on click of Submit

### ISSUE THREAD

**Issue by ttelang** [vadimsva/waitMe#3]
_Environment_ 
Chrome 40 Firefox 36 or IE 11 on Windows 7 Enterprise SP1

**Steps to Reproduce**
1. Go to URL http://vadimsva.github.io/waitMe/
2. Fill in values at Name, Email & Phone field (or keep it empty)
3. Click on Submit.
4. Choose Any effect (say bounce) 

**Expected Result**
Loading animation should be displayed.
**Actual Result**
Loading animation is NOT displayed for all Effects. Clicking Submit & Stop or Refreshing the page also do NOT start the animation.

**Comment by vadimsva** [comment]
Fixed on 1.09. Thanks

**Comment by ttelang** [comment]
Verified, it works now.Thanks for the fast resolution.
