### ISSUE TITLE
White screen appears during hide 

### ISSUE THREAD

**Issue by Kawinesh** [vadimsva/waitMe#5]
After the hide function is called in samsung galaxy tab 3

A grey screen exact to say the overlay screen stays without the loading image or the loading text.

It vanishes once the orientation of the device is changed.  
![screenshot_2015-07-01-16-23-18 1](https://cloud.githubusercontent.com/assets/6001551/8452977/7d956e24-200d-11e5-8cce-8d3841744352.png)

**Comment by vadimsva** [comment]
Hi, I can't reproduce it. Maybe you are doing something wrong?
