### ISSUE TITLE
Add an global option which is a callback to be called when waitMe element is removed

### ISSUE THREAD

**Issue by ryanlin1986** [vadimsva/waitMe#6]
In scenario like knockoutjs, if we call waitMe first, and ko.applyBindings, we just can not remove waitMe later directly, we need use ko.cleanNode first to clear knockout specific data, or memory leaks.

**Comment by vadimsva** [comment]
Ok, use new 1.14 version.
You can use:
elem.waitMe({..., onClose: function() { } });
or use trigger
elem.on('close', function(){ });

**Comment by ryanlin1986** [comment]
Thanks, that's perfect.

**Comment by burhan07** [comment]
hi,

call 

```
function run_waitMe(effect){
    $('.containerBlock > form').waitMe({
        effect: effect,
        text: 'Please wait...',
        bg: 'rgba(255,255,255,0.7)',
        color:'#000',
        sizeW:'',
        sizeH:'',
        source: 'img.svg',
        onClose: function() {}
    });
}
```

not continue it is loop waitingeffect.  I am atest call javascrtip command.
/*
for example issue 
    function run_waitMe(effect){
        $('.containerBlock > form').waitMe({
            effect: effect,
            text: 'Please wait...',
            bg: 'rgba(255,255,255,0.7)',
            color:'#000',
            sizeW:'',
            sizeH:'',
            source: 'img.svg',
            onClose: function() {}
        });

alert("not continiu"); // this not work alert message 
// j query get data and post 
// and close waiting 
    }
*/
can you help me this issue ?
Thank you for helping. 

Best regards.
Burhan KARADERE

**Comment by vadimsva** [comment]
Hi, I don't understand what your problem

**Comment by burhan07** [comment]
I am called   run_waitMe function 

ajax jquery data post method  if post success  hide wait me not work  and not ajax function 

function run_waitMe(effect){
$('.containerBlock > form').waitMe({
effect: effect,
text: 'Please wait...',
bg: 'rgba(255,255,255,0.7)',
color:'#000',
sizeW:'',
sizeH:'',
source: 'img.svg',
onClose: function() {}
});

// not continue this line 

```
        $.ajax({
            type     : "POST",
            cache    : false,
            url      : url,
            data: $("#divcontent").serializeArray(),
            success  : function(data) {
                $("#location").html(data);

               $('.containerBlock > form').waitMe('hide');

            }
        });
```

**Comment by vadimsva** [comment]
You have error in ajax, data is all html, not $("#divcontent").
Use: 
dataString = $("#divcontent").serializeArray();
$.ajax({
            type     : "POST",
            cache    : false,
            url      : url,
            data: dataString,
            success  : function() {
                $("#location").html(dataString);
               $('.containerBlock > form').waitMe('hide');
            }
        });
