### ISSUE TITLE
iOS Chrome(ver47.0.2526.107) not working

### ISSUE THREAD

**Issue by michael2043** [vadimsva/waitMe#8]
eg:roundBounce

black circle not animating...
I hope can fix it.

waitMe.css
add "-webkit-" to animation,keyframes can fix this problem

eg:
-webkit-animation:roundBounce 1.2s xxxxxxx
-webkit-animation-delay:-1.1s
@-webkit-keyframes roundBounce {
   xxxxxx 
   xxxxxx
}

**Comment by vadimsva** [comment]
Your chrome is very old.
You can use last chrome version 51.0.2704.64

**Comment by michael2043** [comment]
sorry,for some reason,I cannot upgrade latest Chrome version.
because Chrome version>48 websql cannot be supported,my website now is using websql.
can you add -webkit-xxx into waitMe.css to fix this problem

**Comment by vadimsva** [comment]
But if your website using websql, how other people can work with it if they using newest chrome?
This old preffiix was removed after 1.12 version, it allowed to reduce the file size by 6kb.
You can use 1.12 version for this reason or edit some styles for effect that you use on website, by copy styles and add preffix like animation:roundBounce;-webkit-animation:roundBounce
